project_id=""
alert_name="alertsdemos"
condition_threshold="0.001"
condition_duration="60s"
condition_comparison="COMPARISON_GT"
alignment_period   = "60s"
per_series_aligner = "ALIGN_SUM"
display_name = "Test-Notification-Channel"
type         = "email"
email_address = "example@xyz.com"
condition_filter="metric.type=\"compute.googleapis.com/instance/memory/balloon/ram_used\" AND resource.type=\"gce_instance\""
